Iter5
sanek1/metrics-collector pull request #5
Opened 2024-12-02 17:15 UTC by sanek1

iter5 -> first commit

2024-12-04 08:59 UTC, zhark0vv requested changes

2024-12-04 08:59 UTC, zhark0vv commented on internal/handlers/handlers.go
> +type IMetricStorage interface {
1. Нейминг `I` это что-то от C#, для Go очень непривычное. Интерфейсы в го обычно заканчиваются на -`Er` и описывают действие.
2. Здорово, что положил интерфейс по месту использования, но еще лучше сделать его приватным. :)

2024-12-04 08:59 UTC, zhark0vv commented on cmd/agent/main.go
> +		Jar: initCookies(logger),
А какую задачу решают `cookie` здесь?

2024-12-04 08:59 UTC, zhark0vv commented on cmd/agent/main.go
> +	//pollTick := time.NewTicker(Options.pollInterval * time.Second)
Следует избегать неинформативных комментариев.

2024-12-04 08:59 UTC, zhark0vv commented on cmd/server/main.go
> +func InitRouting(ms h.MetricStorage) http.Handler {
Рекомендую вынести роутинг в компонент за пределами main, например, `controller`.
Чем меньше будет main, тем лучше.

2024-12-04 08:59 UTC, zhark0vv commented on cmd/server/flags.go
> +// неэкспортированная переменная flagRunAddr содержит адрес и порт для запуска сервера
Комментарии на русском и на английском в одном проекте.
Стоит выбрать один язык.

2024-12-04 08:59 UTC, zhark0vv commented on internal/config/config .go
> +	TypeMethod = 1
Такие типизации в Go делают через [iota](https://go.dev/wiki/Iota).
Но iota, как правило, объединяет близкие друг к другу константы. Здесь же я вижу некоторое смешение домена, предлагаю, не типизировать их как числа, а типизировать как строки.

2024-12-04 08:59 UTC, zhark0vv commented on internal/validation/validation.go
> +	fmt.Println(message)
Лучше использовать логгер - log/slog/zap и т.п.

2024-12-04 17:55 UTC, sanek1 commented on internal/handlers/handlers.go
> +type IMetricStorage interface {
Изменил IMetricStorage на metricStorager
После .net пока не понимаю где лучше размещать интерфейсы, контроллеры, сервисы

2024-12-04 17:56 UTC, sanek1 commented on cmd/agent/main.go
> +		Jar: initCookies(logger),
Согласен куки не используется дальше по коду

2024-12-04 17:56 UTC, sanek1 commented on cmd/agent/main.go
> +	//pollTick := time.NewTicker(Options.pollInterval * time.Second)
Ненужные комментарии почистил

2024-12-04 17:57 UTC, sanek1 commented on cmd/server/main.go
> +func InitRouting(ms h.MetricStorage) http.Handler {
Вынес роутинг в отдельный контроллер.

2024-12-04 17:58 UTC, sanek1 commented on cmd/server/flags.go
> +// неэкспортированная переменная flagRunAddr содержит адрес и порт для запуска сервера
Это был копипаст из урока, согласен выглядит странно))

2024-12-04 17:59 UTC, sanek1 commented on internal/config/config .go
> +	TypeMethod = 1
iota хорошая идея, но мне не нравится эта конструкция. 
В дальнейшем хочу переписать эту часть на более универсальный подход

2024-12-04 18:00 UTC, sanek1 commented on internal/validation/validation.go
> +	fmt.Println(message)
Валидацию переписал, так же планирую переписать эту часть

2024-12-04 18:00 UTC, sanek1 commented
Залил новую версию кода в эту ветку с исправлениями

2024-12-05 17:44 UTC, sanek1 commented
Реорганизовал структуру приложения

2024-12-05 17:59 UTC, zhark0vv approved these changes

2024-12-05 17:59 UTC, zhark0vv commented on cmd/agent/main.go
> +	fmt.Fprintf(os.Stdout, " Iteration ---------> %d\n\n", PollCount)
Вместо прямой записи в `Stdout` лучше использовать логгер: zap, slog и т.п.

2024-12-11 19:56 UTC, merged